# 2.1与2.2

In [86]:
import numpy as np

In [10]:
# 创建
a = np.array([range(10)], dtype=np.float32)
b = np.zeros(10, dtype=np.int32)
c = np.ones((3,3))
d = np.full((3,3), 3.14)
a, b, c, d

(array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]], dtype=float32),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([[3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14]]))

In [18]:
x1 = np.arange(0, 20, 2)
x2 = np.linspace(0, 1, 5)
x1, x2

(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]))

In [26]:
# 0-1均匀分布随机生成
q1 = np.random.random((3, 3))
# Parameters
# ----------
# loc : float or array_like of floats
#     Mean ("centre") of the distribution.
# scale : float or array_like of floats
#     Standard deviation (spread or "width") of the distribution.
# size
# 正太分布
q2 = np.random.normal(0, 1, (3, 3))
q3 = np.random.randint(10, size=(5, 5))
# 生成单位阵
q4 = np.eye(3)
q1, q2, q3

(array([[0.43536085, 0.47951187, 0.32454604],
        [0.86519097, 0.76757801, 0.75507219],
        [0.96457655, 0.77802494, 0.20252443]]),
 array([[-0.50131152, -0.68205965,  0.90156973],
        [-1.1066894 ,  0.39974027,  0.10340616],
        [-0.76455383,  0.10019615, -1.16247385]]),
 array([[4, 6, 3, 9, 1],
        [5, 9, 6, 7, 7],
        [5, 5, 0, 1, 7],
        [6, 5, 9, 5, 8],
        [6, 3, 4, 5, 4]]))

In [52]:
# 元素访问
# x[start:stop:step]
x = np.arange(1, 10, 1)
y = np.arange(1, 17, 1).reshape(2, 2, 4)
(x, x[::2], x[:5:]), (y, y[0,1,1], y[:,:,::2], )

((array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
  array([1, 3, 5, 7, 9]),
  array([1, 2, 3, 4, 5])),
 (array([[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8]],
  
         [[ 9, 10, 11, 12],
          [13, 14, 15, 16]]]),
  6,
  array([[[ 1,  3],
          [ 5,  7]],
  
         [[ 9, 11],
          [13, 15]]])))

In [54]:
# 注意视图与副本
# numpy的数组切片保存的是视图
x = np.arange(1, 10, 1)
y1 = x[:2]
y2 = x[:2].copy()
x[0] = 10
x, y1, y2

(array([10,  2,  3,  4,  5,  6,  7,  8,  9]), array([10,  2]), array([1, 2]))

In [65]:
# reshape
x = np.array([1,2,3,4]).reshape((-1, 2, 2))
x.shape, x
# np.newaxis???

((1, 2, 2),
 array([[[1, 2],
         [3, 4]]]))

In [85]:
# 数组拼接与分裂
# 向量连接与张量连接有区别
x = np.arange(3).reshape(-1, 3)
y = np.arange(3).reshape(-1, 3)
xy = np.concatenate([x,y], axis=0)
x, y, xy, np.split(xy, [1,2], axis=1)

(array([[0, 1, 2]]),
 array([[0, 1, 2]]),
 array([[0, 1, 2],
        [0, 1, 2]]),
 [array([[0],
         [0]]),
  array([[1],
         [1]]),
  array([[2],
         [2]])])